experiment:
  seed: 42
  epochs: 5

finetune:
  freeze_all: true
  vad_classifier:
    input_dim: 512
    hidden_dim: 512

rep_config:
  lr: 0.000066
  dataset_block:
    dataset_sizes:
      armeni2022: 269
      schoffelen2019: 273
      gwilliams2022: 208
    shared_dim: 512
    use_data_block: true
  encoder:
    channels: 512
    conv_channels: [512, 512, 512, 512]
    ratios: [5, 5, 1]
    dimension: 512
  subject_film:
    subject_embedding:
      dataset_keys: ["gwilliams2022"]
      embedding_dim: 16
    film_module:
      feature_dim: 512
      embedding_dim: 16
  projector:
    input_dim: 2560
    hidden_dim: 2048
  band_predictor:
    input_dim: 2560 # 300 * 5 = 1500
  amp_scale_predictor:
    input_dim: 2560 # 300 * 5 = 1500
    prop: 0.2
  phase_diff_predictor:
    input_dim: 2560 # 300 * 5 = 1500
    prop: 0.5

datamodule_config:
  dataset_preproc_configs:
    gwilliams2022:
      bad_subjects: ["01", "02", "03", "25", "26", "27"]
      slice_len: 0.5
      label_type: "vad"
  dataloader_configs:
    train_ratio: 0.8
    val_ratio: 0.2
    test_ratio: 0.0
    pred_ratio: 0.0
    batch_size: 128
    normalisation:
      n_sample_batches: 8
      per_channel: true
      scaler_conf:
        standard_scaler: