experiment:
  seed: 42
  epochs: 500

finetune:
  freeze_all: true
  voiced_classifier:
    type: "mlp"
    input_dim: 1500
    hidden_dim: 512

rep_config:
  lr: 0.000066
  dataset_block:
    dataset_sizes:
      armeni2022: 269
      schoffelen2019: 273
      gwilliams2022: 208
    shared_dim: 300
    use_data_block: true
  encoder:
    channels: 300
    conv_channels: [256, 512, 768, 1024]
    ratios: [5, 5, 1]
    dimension: 300

datamodule_config:
  dataset_preproc_configs:
    armeni2022:
      bad_subjects: ["002", "003"]
      bad_sessions:
        "001": []
        "002": []
        "003": ["008"]
      slice_len: 0.5
      label_type: "voiced"
  dataloader_configs:
    train_ratio: 0.8
    val_ratio: 0.1
    test_ratio: 0.1
    pred_ratio: 0.0
    batch_size: 128
    normalisation:
      n_sample_batches: 8
      per_channel: true
      scaler_conf:
        standard_scaler: