experiment:
  seed: 42
  epochs: 200

rep_config:
  lr: 0.000066
  dataset_block:
    dataset_sizes:
      armeni2022: 269
      schoffelen2019: 273
      gwilliams2022: 208
    shared_dim: 512
    use_data_block: true
  encoder:
    channels: 512
    conv_channels: [512, 512, 512, 512]
    ratios: [5, 5, 1]
    dimension: 512
  subject_film:
    subject_embedding:
      dataset_keys: ["armeni2022", "schoffelen2019"]
      embedding_dim: 16
    film_module:
      feature_dim: 512
      embedding_dim: 16
  projector:
    input_dim: 2560
    hidden_dim: 2048
  band_predictor:
    input_dim: 2560 # 300 * 5 = 1500
  amp_scale_predictor:
    input_dim: 2560 # 300 * 5 = 1500
    prop: 0.2
  phase_diff_predictor:
    input_dim: 2560 # 300 * 5 = 1500
    prop: 0.5
  vad_classifier:
    input_dim: 512
    hidden_dim: 512

datamodule_config:
  dataset_preproc_configs:
    armeni2022:
      data_path: "/data/engs-pnpl/lina4368/armeni2022"
      preproc_path: "/data/engs-pnpl/lina4368/armeni2022"
      l_freq: 0.5
      h_freq: 125
      resample_freq: 250
      notch_freq: 50
      interpolate_bad_channels: true
      window_len: 0.5
      label: "speech"
      info: ["subject", "subject_id", "dataset"]
      include_subjects: ["001", "002", "003"]
      include_sessions:
        "001": ["001", "002", "003", "004", "006", "007", "008", "009", "010"]
        "002": ["001", "002", "003", "004", "006", "007", "008", "009", "010"]
        "003": ["001", "002", "003", "004", "006", "007", "008", "009", "010"]
      preload: true
      label_delay: 0.02
    schoffelen2019:
      data_path: "/data/engs-pnpl/lina4368/schoffelen2019"
      preproc_path: "/data/engs-pnpl/lina4368/schoffelen2019"
      l_freq: 0.5
      h_freq: 125
      resample_freq: 250
      notch_freq: 50
      interpolate_bad_channels: true
      window_len: 0.5
      info: ["subject", "subject_id", "dataset"]
      include_subjects: ["A2002", "A2003", "A2004", "A2005", "A2006", "A2007", "A2008", "A2009", "A2010", "A2013", "A2014", "A2015", "A2016", "A2017", "A2019", "A2020", "A2021", "A2024", "A2025", "A2027", "A2028", "A2029", "A2030", "A2031", "A2032", "A2033", "A2034", "A2035", "A2037", "A2038", "A2039", "A2040", "A2041", "A2042", "A2046", "A2047", "A2049", "A2050"]
      preload: true
  dataloader_configs:
    train_ratio: 0.8
    val_ratio: 0.1
    test_ratio: 0.1
    pred_ratio: 0.0
    batch_size: 128
    normalisation:
      n_sample_batches: 8
      per_channel: true
      scaler_conf:
        standard_scaler:
