experiment:
  seed: 42
  epochs: 50

rep_config:
  lr: 0.000066
  dataset_block:
    dataset_sizes:
      armeni2022: 269
      schoffelen2019: 273
      gwilliams2022: 208
    shared_dim: 512
    use_data_block: true
  subject_film:
    subject_embedding:
      dataset_keys: ["armeni2022", "schoffelen2019"]
      embedding_dim: 16
    film_module:
      feature_dim: 512
      embedding_dim: 16
  vad_classifier_linear:
    input_dim: 512
    hidden_dim: 512

datamodule_config:
  dataset_preproc_configs:
    armeni2022:
      data_path: "/data/engs-pnpl/lina4368/armeni2022"
      preproc_path: "/data/engs-pnpl/lina4368/armeni2022"
      l_freq: 0.5
      h_freq: 125
      resample_freq: 250
      notch_freq: 50
      interpolate_bad_channels: true
      window_len: 0.5
      label: "speech"
      info: ["subject", "subject_id", "dataset"]
      preload: true
      label_delay: 0.02
  dataloader_configs:
    train_ratio: 0.8
    val_ratio: 0.1
    test_ratio: 0.1
    pred_ratio: 0.0
    batch_size: 128
    normalisation:
      n_sample_batches: 8
      per_channel: true
      scaler_conf:
        standard_scaler:
