experiment:
  seed: 42
  epochs: 10000
  lr: 0.0003

stats:
  iter_update_freq: 200

data:

  slice_len: 2.0 # Same as Moses et al.
  train_ratio: 0.95
  batch_size: 32
  label_type: "vad"
  exclude_subjects: ["002", "003"]

  norm:
    n_sample_batches: 8
    per_channel: True
    scaler_conf:
      standard_scaler:

  dataset_sizes:
    Armeni2022: 266
  
  preproc_config:
    armeni2022:
      filtering: True
      resample: 300
      notch_freqs: [50, 100, 150]
      bandpass_lo: 0.5
      bandpass_hi: 150

model:
  lstm:
    feature_dim: 266
    hidden_dim: 128
    num_layers: 2
    output_classes: 2
    sub_block: