experiment:
  seed: 42
  epochs: 10000
  lr: 0.0003

stats:
  iter_update_freq: 100

data:

  slice_len: 3.0
  train_ratio: 0.95
  batch_size: 32
  label_type: "vad"
  exclude_subjects: []

  norm:
    n_sample_batches: 8
    per_channel: True
    scaler_conf:
      standard_scaler:

  dataset_sizes:
    Armeni2022: 269
  
  preproc_config:
    armeni2022:
      filtering: True
      resample: 250
      notch_freqs: [50, 100]
      bandpass_lo: 0.5
      bandpass_hi: 125

tokenizer:
  seanet:
    vq_dim: 64
    codebook_size: 1024
    shared_dim: 300
    ratios: [1]
    conv_channels: [512, 512]
    data_block:
  state_dict: "/data/engs-pnpl/lina4368/experiments/exp_20240215-212402_effusive-dove-249/102000.pt"
  dataset_sizes:
    Armeni2022: 269
  debug:

model:
  mlp:
    feature_dim: 512
    hidden_dim: 256
    output_classes: 2
    sub_block:
    data_block: