experiment:
  seed: 42
  epochs: 10000
  lr: 0.0003 # 0.0003 * sqrt(32 / 4)

stats:
  iter_update_freq: 1000

data:

  slice_len: 0.4  # Same as Moses et al.
  train_ratio: 0.98
  batch_size: 16 # Previously: 4

  norm:
    n_sample_batches: 4
    per_channel: True
    scaler_conf:
      standard_scaler:

  dataset_sizes:
    Gwilliams2022: 208
  
  preproc_config:
    gwilliams2022:
      filtering: True
      resample: 250
      notch_freqs: [50, 100]
      bandpass_lo: 0.5
      bandpass_hi: 125

model:
  seanet:
    vq_dim: 64
    codebook_size: 1024
    shared_dim: 300
    ratios: [2, 1, 1]
    conv_channels: [512, 512, 512, 512]
    # sub_block:
    data_block: