experiment:
  seed: 42
  epochs: 10000
  lr: 0.0003

stats:
  iter_update_freq: 200

data:

  slice_len: 0.3
  train_ratio: 0.95
  batch_size: 32
  label_type: "voiced"
  exclude_subjects: []

  norm:
    n_sample_batches: 8
    per_channel: True
    scaler_conf:
      standard_scaler:

  dataset_sizes:
    Gwilliams2022: 208
  
  preproc_config:
    gwilliams2022:
      filtering: True
      resample: 250
      notch_freqs: [50, 100]
      bandpass_lo: 0.5
      bandpass_hi: 125

model:
  lstm:
    feature_dim: 208
    hidden_dim: 128
    num_layers: 2
    output_classes: 2
    sub_block: