experiment:
  seed: 42
  epochs: 1000
  lr: 0.0003

stats:
  iter_update_freq: 200

data:

  slice_len: 3.0
  train_ratio: 0.95
  batch_size: 32

  norm:
    n_sample_batches: 8
    per_channel: True
    scaler_conf:
      # standard_scaler:
      robust_scaler:
        lo_q: 0.25
        hi_q: 0.75

  dataset_sizes:
    Gwilliams2022: 208
  
  preproc_config:
    gwilliams2022:
      filtering: True
      resample: 300
      notch_freqs: [50, 100, 150]
      bandpass_lo: 0.5
      bandpass_hi: 150

model:
  short:
    vq_dim: 64
    codebook_size: 1024
    shared_dim: 300
    hidden_dim: 512